In [5]:
import numpy as np

X = np.matrix([[1, 2, 3], [4, 5, 6]])


Z = X[:, 1]
Z

Z.T * Z

matrix([[29]])

In [6]:
theta = np.matrix([[1], [2], [1]])
theta

matrix([[1],
        [2],
        [1]])

In [7]:
y = np.matrix([[1], [1]])
y

matrix([[1],
        [1]])

In [8]:
term = X * theta - y

term

matrix([[ 7],
        [19]])

In [9]:
a = np.matrix(3 * [1]).T
a

matrix([[1],
        [1],
        [1]])

In [10]:
import math

a[1] = 2

math.sqrt(6)

np.linalg.norm(a)

2.4494897427831779

In [11]:
x = np.matrix([1, -2, 3, -4])
x

matrix([[ 1, -2,  3, -4]])

In [12]:
x_abs = [abs(x_i) for x_i in x]
x_abs

[matrix([[1, 2, 3, 4]])]

In [14]:
type(X)

numpy.matrixlib.defmatrix.matrix