In [49]:
import numpy as np

def optimize_theta(X, y, lamb):
    n_rows = X.shape[0]
    n_cols = X.shape[1]
    
    theta = np.matrix(n_cols * [1]).T
    change_in_theta = 1
    
    while change_in_theta > 1e-5:
        theta_new = np.matrix.copy(theta)
        
        for i in len(theta):
            X_i = X[:,i]
            X_term = X_i * (X * theta_new - y)
            
            denom = X_i.T * X_i
            numerator_neg = lamb - X_term
            numerator_pos = -1 * lamb - X_term
            
            theta_i_neg = min(numerator_neg/denom, 0)
            theta_i_pos = max(numerator_pos/denom, 0)
            
            theta_new[i] = theta_i_pos
            obj_theta_i_pos = 0.5 * np.linalg.norm(X * theta_new - y)**2 + lamb * sum([abs(theta_i) for theta_i in theta_new])
            
            theta_new[i] = theta_i_neg
            obj_theta_i_neg = 0.5 * np.linalg.norm(X * theta_new - y)**2 + lamb * sum([abs(theta_i) for theta_i in theta_new])
            
            if obj_theta_i_pos < obj_theta_i_neg:
                theta_new[i] = theta_i_pos
            else:
                theta_new[i] = theta_i_neg
            
        change_in_theta = np.matrix.norm(theta - theta_new)
        theta = np.matrix.copy(theta_new)
        
    return theta
    

In [32]:
X = np.matrix([[1, 2, 3], [4, 5, 6]])


Z = X[:, 1]
Z

Z.T * Z

matrix([[29]])

In [19]:
theta = np.matrix([[1], [2], [1]])
theta

matrix([[1],
        [2],
        [1]])

In [20]:
y = np.matrix([[1], [1]])
y

matrix([[1],
        [1]])

In [22]:
term = X * theta - y

term

matrix([[ 7],
        [19]])

In [33]:
a = np.matrix(3 * [1]).T
a

matrix([[1],
        [1],
        [1]])

In [48]:
import math

a[1] = 2

math.sqrt(6)

np.linalg.norm(a)

2.4494897427831779

In [53]:
x = np.matrix([1, -2, 3, -4])
x

matrix([[ 1, -2,  3, -4]])

In [54]:
x_abs = [abs(x_i) for x_i in x]
x_abs

[matrix([[1, 2, 3, 4]])]